### ISSUE TITLE
Frequent Reconnects w/ "Error: Short read"

### ISSUE THREAD

**Issue by MTecknology** [jgeboski/bitlbee-facebook#10]
About every three hours, I end up with "Error: Short read" errors that cause a disconnect. This causes any open chats I have open to be closed and then after reconnecting the chat is closed so any messages received during that time are lost without logging into the web interface.

Because of the frequency of disconnects and the issues that come with them, this amazing feature becomes pretty much unusable. :(

This /might/ be related to #2 but I'm not sure.

**Comment by jgeboski** [comment]
Yeah, I am leading towards this being a side effect of #2.  I will leave the issue open for now, until a fix for #2 confirms this as being resolved.

**Comment by jgeboski** [comment]
This should be resolved as of 059b686.
