### ISSUE TITLE
A bit more advice for clueless

### ISSUE THREAD

**Issue by mcepl** [jgeboski/bitlbee-facebook#11]
When I try to connect using login and password I use for logging-in via the browser, e.g. something like
```
account add facebook mcepl somethingverysecret
account facebook on
```
I get incorrect login or password error (password is copied from the browser via clipboard, so it should be OK). What's wrong?

**Comment by toogy** [comment]
Why not using an app password instead? It works perfectly fine and it's more secure.

**Comment by jgeboski** [comment]
Try using your email instead of your username.

**Comment by mcepl** [comment]
> Why not using an app password instead? It works perfectly fine and it's more secure.

Because I am lazy and I am just testing whether your plugin works at all.

> Try using your email instead of your username.

Thanks. That works.
