### ISSUE TITLE
Constant Connection Timeouts

### ISSUE THREAD

**Issue by jgeboski** [jgeboski/bitlbee-facebook#2]
The MQTT connection randomly drops out, and the account is forced to log back in.  This leads to messages becoming lost in transit to the client.

To resolve this issue, the plugin should attempt to silently reconnect with the last sequence identifier.  Using the last sequence identifier will enable the plugin to retrieving missed messages.

**Comment by ypnos** [comment]
For me the current situation is unusable. Reconnects happen all the time and about 20% to 30% of messages I would receive are lost

**Comment by jgeboski** [comment]
Fixed as of 059b686.
