### ISSUE TITLE
"imcb_buddy_status() for unknown handle" when receiving messages from new friends

### ISSUE THREAD

**Issue by scgtrp** [jgeboski/bitlbee-facebook#22]
I accepted a friend request on Facebook's website while connected via Bitlbee. That person then tried to send me a message. I did not receive the message in my IRC client, but I did see several instances of this in the control channel at that time:

```
13:51 <@root> facebook - imcb_buddy_status() for unknown handle [redacted]:
13:51 <@root> flags = 1, state = NULL, message = NULL
```

Having Bitlbee disconnect and reconnect to Facebook seems to have caused it to notice that person, fixing the issue.

**Comment by jgeboski** [comment]
This is on the TODO list in #1.  Just cramped on time lately.

**Comment by jgeboski** [comment]
For now, just reconnect the account:

```
account <acc> off
account <acc> on
```

**Comment by jgeboski** [comment]
This is on the TODO list already, closing for now.
