### ISSUE TITLE
Not getting sound notifications on mobile anymore

### ISSUE THREAD

**Issue by kirbo** [jgeboski/bitlbee-facebook#25]
I didn't notice there was any issue created for this "bug" and I don't know does it even have anything to do with this module, or is there some sort of new feature in Facebook API or something, but here goes:

A while ago my iPhone stopped giving me a sound/vibration notifications for new facebook messages. I've tried every possible setting in my iPhone and reinstalled Messenger, with no luck.

I've noticed that when I turn off my bitlbee-facebook ```account facebook off``` I do get notifications on my phone as usual and when my bitlbee-facebook is online, I only get onscreen banner notifications, without any sound or vibrate. Even away messages make no difference.

Any idea what should be done to get the notifications work as they should?

I have Messenger version 26.0 and iOS 8.4 (12H4086d) and bitlbee Version: 3.2.2-2+b1, bitlbee-common Version: 3.2.2-2, bitlbee-facebook commit: ea5d6af3cecd01222172324d320718ff629e3a7f.

**Comment by jgeboski** [comment]
Sounds like a limitation or issue with the Messenger platform?

**Comment by maxux** [comment]
I have the same issue on my iPhone. Seems to be facebook-side limitation :(

**Comment by jgeboski** [comment]
Yeah, I am not sure we have much control over this.

**Comment by jgeboski** [comment]
As previously stated, I do not think we have much control over this.  It is probably just a side effect of running more than one Messenger client at the same time.  That said, I am closing this for now, if anything happens to be found out in the future, we'll address it then.
