### ISSUE TITLE
Release-handling?

### ISSUE THREAD

**Issue by fuzzy76** [jgeboski/bitlbee-facebook#27]
I prefer not to compile my own software. Do you have any plan of contributing this back to the bitlbee project or do distro packaging?

**Comment by jgeboski** [comment]
For Debian: http://dl.voidium.net/jgeboski/

**Comment by jgeboski** [comment]
I am considering using build.opensuse.org.  Anyone have any experience with OBS?

**Comment by jgeboski** [comment]
I have written instructions for purple-facebook, they're mostly the same for bitlbee-facebook.  Just swap "bitlbee" in-place of "purple."

https://github.com/jgeboski/purple-facebook/wiki/Installing-on-*NIX#debian-and-ubuntu

**Comment by jgeboski** [comment]
What distribution are you using?

**Comment by jgeboski** [comment]
Closing this due to lack of information.

**Comment by fuzzy76** [comment]
Sorry about that. It's Debian.
