### ISSUE TITLE
Shorten fb* commands with a single account

### ISSUE THREAD

**Issue by Zopieux** [jgeboski/bitlbee-facebook#3]
It is quite cumbersome being forced to type `facebook` (or whatever the tag is) on `fbchats`/`fbcreate`/`fbjoin` commands because when there is a single facebook account, it is not ambiguous.

I don't know if bitlbee API makes this possible, but if it is, that would be great!

**Comment by jgeboski** [comment]
Agreed.

**Comment by jgeboski** [comment]
Implemented in the `development` branch.

**Comment by Zopieux** [comment]
That was quick! Kudos.
