### ISSUE TITLE
Bitlbee disconnects on "acc facebook on"

### ISSUE THREAD

**Issue by TedTed** [jgeboski/bitlbee-facebook#31]
Hello,

I'm using bitlbee 3.2.2-2+b1 with bitlbee-facebook 0.1+20150528+master+d43bd0a+jessie on Debian Jessie.

I can connect to bitlbee just fine using "/connect localhost" in irssi. Then, I add a facebook account using "acc add facebook myaddress@example.com myappspecificpassword", and when I use "acc facebook on", bitlbee just disconnects. When doing this while running bitlbee manually with "BITLBEE_DEBUG=1 /usr/sbin/bitlbee -nD", I'm getting the following message:
Error: Fatal signal received: 11. That's probably a bug.
Segmentation fault

I guess the problem comes from this plugin, since I've never had this problem before, but if I need to post something in bitlbee's bug tracker, let me know.

**Comment by jgeboski** [comment]
Run `bt` in gdb when it segfaults.

**Comment by dequis** [comment]
Sounds like mixing a bitlbee 3.2.2 with a bitlbee-facebook meant to be used with 3.4

Use the apt repo from http://code.bitlbee.org/debian/ instead of the bitlbee from jessie.

**Comment by jgeboski** [comment]
Closing due to lack of response.

**Comment by konaya** [comment]
This still happens. This *is* a bug in the packaging of bitlbee-facebook, as it should depend on bitlbee >=3.4 if it will fail with earlier versions.

**Comment by dequis** [comment]
But it does.

https://github.com/jgeboski/bitlbee-facebook/blob/master/configure.ac#L79

```
PKG_CHECK_MODULES([BITLBEE], [bitlbee >= 3.4])
```

**Comment by jgeboski** [comment]
The debian stuff needs to be updated.
