### ISSUE TITLE
List dependencies

### ISSUE THREAD

**Issue by ayonix** [jgeboski/bitlbee-facebook#34]
I tried to build it and had to install following packages on debian stretch/sid:
* autoconf
* libtool
* libglib2.0-dev

**Comment by jgeboski** [comment]
Okay?

**Comment by Zopieux** [comment]
@ayonix I suggest you edit the README (maybe online if you're in a hurry!) with such a list and open a PR.

**Comment by jgeboski** [comment]
Or you just open up configure.ac and look for the dependencies, which will just be `autoconf` and `libtool` in your case.  All other dependencies will be installed by `apt-get build-dep bitlbee`.  I have no intentions of having specific build instructions for every distribution, but rather generic ones.
