### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by scuba323** [jgeboski/bitlbee-facebook#35]
I am sure I am getting a error due to dependencies, but this is what I am getting;

Can't exec "libtoolize": No such file or directory at /usr/bin/autoreconf line 196.
Use of uninitialized value in pattern match (m//) at /usr/bin/autoreconf line 196.
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -Im4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:32: error: possibly undefined macro: AC_DISABLE_STATIC
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:33: error: possibly undefined macro: AC_PROG_LIBTOOL
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by ayonix** [comment]
Seems like 'libtool' is missing. If you see something else you could report in #34

**Comment by dequis** [comment]
out of curiosity, what distro is this?

**Comment by scuba323** [comment]
Elementary OS. Luna I believe. I will install libtool and report back! :)
