### ISSUE TITLE
Autojoin chats already fbjoined when receiving a message

### ISSUE THREAD

**Issue by seirl** [jgeboski/bitlbee-facebook#38]
01:58 <seirl> do you autojoin a group when receiving a message yet?
    01:58 <jgeboski> no
    01:58 <jgeboski> I don't know how I want to do the naming for that
    01:58 <jgeboski> like wtf to you name the channel?
    [...]
    01:59 <seirl> what you could do is do that only for the channels you already explicitely joined then leaved
    02:00 <jgeboski> so, if there is already a bitlbee channel, and the user is not in it via their client, open it?
    02:00 <jgeboski> assuming there is an incoming message?
    02:00 <seirl> yes     
    02:00 <jgeboski> yeah, I could do that
    02:00 <jgeboski> seems fairly sane

**Comment by andreimarcu** [comment]
is there a public irc channel for this?

**Comment by seirl** [comment]
Not really, just `#bitlbee@irc.bitlbee.org`

**Comment by andreimarcu** [comment]
Thanks!

**Comment by jgeboski** [comment]
Implemented as of 073a946.
