### ISSUE TITLE
Message from strangers printed out in main &bitlbee channel

### ISSUE THREAD

**Issue by ycny** [jgeboski/bitlbee-facebook#39]
Hi

I'm using weechat for IRC, bitlbee for jabber and facebook conversations. I've grouped my jabber and facebook contacts following this guide https://wiki.bitlbee.org/ManagingContactList
Everything is ok, I have my facebook contacts in &facebook. When someone is writing to me, the new private channel appears with his ID. 
The problem is when sender is a stranger (not my friend on facebook) the message goes to &bitlbee main channel, instead of new private channel. It'd be great to see this conversation in the same place as the others and to be able to answer. 
The sender is actually an administrator of some "fan page". Message was in my "Inbox", not in "Other".

In &bitlbee:

    acc list
    0 (facebook): facebook, ... 
    1 (jabber): jabber, ...

**Comment by dequis** [comment]
>< dx> help set handle_unknown
>< root> Type: string
>< root> Scope: global
>< root> Default: add_channel
>< root> Possible Values: root, add, add_private, add_channel, ignore
>< root>
>< root> By default, messages from people who aren't in your contact list are shown in a control channel instead of as a private message.
>< root>
>< root> If you prefer to ignore messages from people you don't know, you can set this one to "ignore". "add_private" and "add_channel" are like add, but you can use them to make messages from unknown buddies appear in the channel instead of a query window.
>< root>
>< root> Although these users will appear in your control channel, they aren't added to your real contact list. When you restart BitlBee, these auto-added users will be gone. If you want to keep someone in your list, you have to fixate the add using the add command.
