### ISSUE TITLE
Autojoin after fbjoin command

### ISSUE THREAD

**Issue by Zopieux** [jgeboski/bitlbee-facebook#4]
IRC protocol lets the server force a user to join a channel. bitlbee-facebook could use this feature to auto-join the channel created with the `fbjoin` command.

I guess this should be optional and an `autojoin` boolean setting could be added.

**Comment by jgeboski** [comment]
Implemented in the `development` branch.

**Comment by Zopieux** [comment]
That was quick! Kudos.
