### ISSUE TITLE
The API seems to "consume" messages before they reach other devices

### ISSUE THREAD

**Issue by BlackLight** [jgeboski/bitlbee-facebook#40]
Every time I receive a message and bitlbee-facebook is on, a message-read notification is sent to the Facebook server and therefore:

* It looks like the message was read, even if we just left an SSH session with irssi open on some remote server;

* The message doesn't reach any other devices connected to the account. I experienced it today: while bitlbee-facebook was on, I wasn't able to get the message notifications either on my tablet or smartphone, although I hadn't read the message yet.

I don't know if it's a common issue, a design flaw in the API, or if it's some misconfiguration on my side.

**Comment by dequis** [comment]
`account facebook set mark_read false`

**Comment by BlackLight** [comment]
Thanks, that worked.

Just two last points:

1. Wouldn't it be a good idea to make it the default behaviour? Most of the people using bitlbee-facebook used to use the plain Facebook over Jabber for bitlbee before, which behaved that way, and it would be more consistent. Also, I don't think many users want to immediately notify their friends whenever they receive a message.

2. Wouldn't it be a good idea to document these settings? I see now that mark_read is defined and assigned in facebook.c, together with show_unread and sync_interval, but unless I open the code there's no way to be aware of the existence of those settings through the README nor any provided documentation.

**Comment by todoleza** [comment]
Thanks to this and other report I discovered why notifications on my phone (using Disa) stopped working recently. As my bitlbee instance is running 24/7 I haven't discovered this myself.
I also suggest documenting this and making mark_read=false a default setting if possible.

**Comment by dequis** [comment]
#42

https://wiki.bitlbee.org/HowtoFacebookMQTT#Settings
