### ISSUE TITLE
fedora package

### ISSUE THREAD

**Issue by larsks** [jgeboski/bitlbee-facebook#45]
On the odd chance that it might be useful to someone, I've put together a package for CentOS (7) and Fedora (22, 23, rawhide) of this available via COPR at <https://copr.fedoraproject.org/coprs/larsks/bitlbee-facebook/>.

To use it:

    dnf -y install 'dnf-command(copr)'
    dnf -y copr enable larsks/bitlbee-facebook
    dnf -y install bitlbee-facebook

**Comment by jgeboski** [comment]
Nice!

I was unaware of Copr, looks much nicer than OBS. Does it only support Fedora/CentOS?

**Comment by larsks** [comment]
> Does it only support Fedora/CentOS?

Well, Fedora and any RHEL derivatives that can use the [EPEL](https://fedoraproject.org/wiki/EPEL) repositories (so RHEL itself, CentOS, probably Scientific Linux...).

**Comment by jgeboski** [comment]
Closing this issue as there is nothing more to resolve on the matter.
