### ISSUE TITLE
Add a way to remove someone from a chat

### ISSUE THREAD

**Issue by seirl** [jgeboski/bitlbee-facebook#5]
I know this might be a problem since bitlbee can't handle the KICK command... Is there a workaround for that?

**Comment by jgeboski** [comment]
Frankly, I would really like to see bitlbee support `KICK`.  It makes the most sense, and would keep things consistent with the support of `INVITE`.  As a last resort, I am sure we can always hack something into the bitlbee interface, much like with what was done with the root commands.

@dequis, any chance of bitlbee supporting `KICK` in group chats, much like with `INVITE`?

**Comment by dequis** [comment]
Patches welcome™

**Comment by jgeboski** [comment]
Waiting on bitlbee/bitlbee#13.

**Comment by dgw** [comment]
bitlbee/bitlbee#13 is merged, in case that's news to anyone in this thread.

**Comment by seirl** [comment]
02:03 <jgeboski> also, I can do your /kick thing now

**Comment by jgeboski** [comment]
Implemented as of 2c6233a.
