### ISSUE TITLE
Topic change event

### ISSUE THREAD

**Issue by seirl** [jgeboski/bitlbee-facebook#50]
While /topic works to change the topic from bitlbee, it would be nice to be notified in bitlbee when the topic is changed by a different client. If we don't change the topic ourselves, it stays the same whatever happens to it in the server.

**Comment by jgeboski** [comment]
Works for me as of the latest revision.

**Comment by jgeboski** [comment]
Closing due to lack of reply.

**Comment by dequis** [comment]
@seirl u suk
