### ISSUE TITLE
Protocol not found

### ISSUE THREAD

**Issue by gregoriosw** [jgeboski/bitlbee-facebook#51]
I have installed the nightly repo for Debian Wheezy and updated bitlbee to 3.4.1 and then installed the bitlbee-facebook repo and installed bitlbee-facebook.  I have also restarted weechat in which I run bitlbee.  On reconnecting to bitlbee and trying to add a facebook account with 

acc add facebook email@foo.com password

I receive the response from bitlbee of "Unknown Protocol".  

I've checked everything is installed and running the correct version etc.  Any thoughts as to why this isn't working.  Facebook.so is in /usr/lib/bitlbee.

Any hints gratefully received.
Greg

**Comment by dequis** [comment]
Do you have `Protocols` set to anything in /etc/bitlbee/bitlbee.conf? If so, comment the line out.

If that doesn't help, type `ldd /usr/lib/bitlbee/facebook.so` in a shell, see if the output mentions any errors

**Comment by gregoriosw** [comment]
The protocols line was commented out.  

The ldd output is...

 linux-vdso.so.1 =>  (0x00007ffe07132000)
        libjson-glib-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libjson-glib-1.0.so.0 (0x00007fd6a73fa000)
        libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007fd6a70a7000)
        libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007fd6a6e56000)
        libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fd6a6b5e000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fd6a6947000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd6a672a000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd6a639f000)
        libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007fd6a619b000)
        libgthread-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0 (0x00007fd6a5f98000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fd6a5d90000)
        libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007fd6a5b70000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fd6a5959000)
        libffi.so.5 => /usr/lib/x86_64-linux-gnu/libffi.so.5 (0x00007fd6a574c000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fd6a550f000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd6a7855000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd6a530a000)

Does this help in any way to understand what is happening as there is no obvious error.

**Comment by dequis** [comment]
Hmm. Should probably have asked this before but:

>I have also restarted weechat in which I run bitlbee.

Restarting weechat is not needed. Did you also restart the bitlbee daemon?

**Comment by gregoriosw** [comment]
Restarted daemon and all is working now. 
Thanks for the help.
