### ISSUE TITLE
Query to one self

### ISSUE THREAD

**Issue by dal00** [jgeboski/bitlbee-facebook#54]
When I have a query/chat opened with a friend and I write in the mobile app (not tested the web-chat) all my messages show up as a query with myself in bitlbee.

Connected with irssi and using the deb package from your repo: 20151113~f2ca48a~16

Hope you understand what I mean :)

(Thanks for this excellent piece of software, so nice not to be able to use a proper client)

**Comment by dequis** [comment]
`help set self_messages`

**Comment by dal00** [comment]
Thanks for the quick answer, setting it to "prefix" solved it!

**Comment by dequis** [comment]
Yay!

**Comment by dal00** [comment]
So I have an update for the record.
This https://github.com/bitlbee/bitlbee/commit/345577bc90da1d1fffa0df013426eab54fa2b1b2 explains that I need to run the latest irssi (0.8.18), so I will upgrade and then I won't have to use the ugly prefix workaround..
