### ISSUE TITLE
Lower glib2 requirement to 2.28.8

### ISSUE THREAD

**Issue by robert-scheck** [jgeboski/bitlbee-facebook#55]
Is it possible to lower the glib2 requirement from 2.32.0 to 2.28.8, please? This would allow to build bitlbee-facebook for RHEL/CentOS 6.

**Comment by dequis** [comment]
So I tried forcing an install in a centos6 docker. Results:

>< dx> rsc jgeboski: ok so, main problem, centos6 doesn't have json-glib, but i installed it manually. there are errors about G_VALUE_INIT, but it can be replaced with "{0}". after that, it's missing g_queue_free_full() and g_byte_array_new_take(). the former can be replaced with iteration over the queue, the latter i'm not sure, looks tricky.
>< jgeboski> latter is easy
>< dx> what is it, just creating an empty array and appending?
>< jgeboski> I'd have to look
>< dx> not so easy then!
>< jgeboski> I did it for purple
>< dx> oh, huh
>< jgeboski> its in the glibcompat.h
>< jgeboski> unless that got yanked
>< dx> neat, it is
>< dx> the three relevant defs are there
>< jgeboski> might be best if we just create a local facebook-glib.h
>< jgeboski> then include that instead of glib.h
>< jgeboski> and just do compact stuff in that
>< jgeboski> is json-glib even in centos?
>< dx> it's not in centos6, it's in centos7
>< dx> not sure if rsc can package that
>< dx> json-glib 0.14 is the minimum version supported by bitlbee-facebook and it's also the only version that supports glib 2.28 (it says minimum 2.26, next version says minimum 2.34)
>< dx> oh also
>< dx> -AM_GNU_GETTEXT_VERSION([0.18])
>< dx> +AM_GNU_GETTEXT_VERSION([0.17])
>< dx> had to do that in json-glib for it to build, lol.

So this plugin can work by changing the requirement in configure.ac and using these defines https://bitbucket.org/pidgin/main/src/404282320cf8468c338c53e3eebe34bc5bcd3681/libpurple/glibcompat.h?at=default&fileviewer=file-view-default#glibcompat.h-79

The main problem is the json-glib requirement, which isn't packaged for centos6

**Comment by robert-scheck** [comment]
I will package/maintain a suitable version of json-glib for EPEL 6, if that is needed.

**Comment by jgeboski** [comment]
Resolved as of 04cc3a0.
