### ISSUE TITLE
Sent messages from other clients are whispered to myself

### ISSUE THREAD

**Issue by DesktopMan** [jgeboski/bitlbee-facebook#58]
If I talk to someone using the mobile app anything I say is whispered to myself in Bitlbee, as myself. The message does not show in the chat with the person I am actually talking to, but their messages are. Is there a way to work around this issue?

**Comment by dal00** [comment]
If you mean in a query to your self then #54 might have your answer.
Your client needs to support it if you don't want to use a workaround.

**Comment by DesktopMan** [comment]
Is it possible for these to occur "from myself" like messages I sent from Bitlbee? Prefix works but looks different.

**Comment by jgeboski** [comment]
@DesktopMan see the [documentation](https://wiki.bitlbee.org/SelfMessages) on self messages.
