### ISSUE TITLE
Timeout during connect

### ISSUE THREAD

**Issue by mas90** [jgeboski/bitlbee-facebook#63]
Whenever I try to connect to Facebook:

`01:32:18 <@malc> account facebook on`
`01:32:19 <@root> facebook - Logging in: Authenticating`
`01:32:20 <@root> facebook - Logging in: Fetching contacts`
`01:32:23 <@root> facebook - Logging in: Connecting`
`01:34:18 <@root> facebook - Login error: Connection timeout`
`01:34:18 <@root> facebook - Logging in: Signing off..`
`01:34:18 <@root> facebook - Logging in: Reconnecting in 45 seconds..`

The debug log suggests that it's fetched my contacts list etc., but then hangs indefinitely before completing the connection.

Any clues?

**Comment by jgeboski** [comment]
Are you using IPv6 on your system?

**Comment by mas90** [comment]
I am; is that a problem?

**Comment by jgeboski** [comment]
What does `ping6 mqtt.facebook.com` say?

**Comment by mas90** [comment]
Seems fine:

PING mqtt.facebook.com(mqtt6-shv-07-ash3.facebook.com) 56 data bytes
64 bytes from mqtt6-shv-07-ash3.facebook.com: icmp_seq=1 ttl=41 time=216 ms
64 bytes from mqtt6-shv-07-ash3.facebook.com: icmp_seq=2 ttl=41 time=216 ms
64 bytes from mqtt6-shv-07-ash3.facebook.com: icmp_seq=3 ttl=41 time=216 ms
64 bytes from mqtt6-shv-07-ash3.facebook.com: icmp_seq=4 ttl=41 time=216 ms
64 bytes from mqtt6-shv-07-ash3.facebook.com: icmp_seq=5 ttl=41 time=216 ms
^C
--- mqtt.facebook.com ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4005ms
rtt min/avg/max/mdev = 216.761/216.824/216.890/0.591 ms

**Comment by jgeboski** [comment]
Paste a few lines of the debug output right before it stops. Make sure you strip out any unique identifiers before posting.

**Comment by mas90** [comment]
An abridged version of the last logged request/response is:

```
[INFO] facebook: POST Request (0xb8d2ac30): https://graph.facebook.com/graphql
[INFO] facebook:   Content-Type: application/x-www-form-urlencoded
[INFO] facebook:   Connection: Close
[INFO] facebook:   Accept: */*
[INFO] facebook:   Content-Length: 286
[INFO] facebook:   Host: graph.facebook.com
[INFO] facebook:   Authorization: OAuth [ELIDED]
[INFO] facebook:
[INFO] facebook:   fb_api_req_friendly_name=FetchContactsFullQuery&locale=en_GB&query_params=[ELIDED]
[INFO] facebook: POST Response (0xb8d2ac30): https://graph.facebook.com/graphql (200 OK)
[INFO] facebook:   HTTP/1.1 200 OK
[INFO] facebook:   ETag: "[ELIDED]"
[INFO] facebook:   fb-graphql-error-count: 0
[INFO] facebook:   Content-Type: application/json; charset=UTF-8
[INFO] facebook:   Facebook-API-Version: v1.0
[INFO] facebook:   Access-Control-Expose-Headers: X-FB-Debug
[INFO] facebook:   Access-Control-Allow-Credentials: true
[INFO] facebook:   Expires: Sat, 01 Jan 2000 00:00:00 GMT
[INFO] facebook:   Access-Control-Allow-Method: , OPTIONS
[INFO] facebook:   Cache-Control: private, no-cache, no-store, must-revalidate
[INFO] facebook:   Pragma: no-cache
[INFO] facebook:   Vary: Origin
[INFO] facebook:   X-FB-Rev: 2168097
[INFO] facebook:   X-FB-Trace-ID: [ELIDED]
[INFO] facebook:   Access-Control-Allow-Origin: https://graph.facebook.com
[INFO] facebook:   Vary: Accept-Encoding
[INFO] facebook:   X-FB-Debug: [ELIDED]
[INFO] facebook:   Date: Sun, 07 Feb 2016 01:48:51 GMT
[INFO] facebook:   Connection: close
[INFO] facebook:   Content-Length: 969238
[INFO] facebook:
[INFO] facebook:   {"viewer":{"messenger_contacts":{"sync_id":"0","nodes":[{"added_time":1328772626,"bigPictureUrl":{"uri":"[ELIDED]","width":50},"graph_api_write_id":"contact_[ELIDED]","hugePictureUrl":{"uri":"[ELIDED]","width":50},"id":"[ELIDED]","imported_phone_entries":[],"is_on_viewer_contact_list":true,"name_entries":[{"primary_field":{"__type__":{"name":"MessengerContactName"},"value":{"text":...[VERY LONG LINE TRUNCATED (apparently my full contacts list)]
[INFO] facebook: Parsing JSON: [AS ABOVE]
```

It hangs after "Parsing JSON".  Maybe it's just taking more than two minutes to parse that 969kB JSON response!

**Comment by jgeboski** [comment]
Is it actually hanging, or does it just fail to connect? More specifically, is bitlbee actually locking up?

**Comment by dequis** [comment]
It's just the same timeout other people were reporting before. Some routing problem. My hetzner box was affected once, reconnected to some other IP in the round robin and it just worked. Other connections never had issues.

**Comment by mas90** [comment]
@jgeboski Sorry, I meant that it just fails to connect.  I can still interact with the root bitlbee user.

@dequis My IPv6 connectivity to Facebook seems to be working.  Plausibly a subtle network performance issue though.

**Comment by jgeboski** [comment]
Are you running the latest version of the plugin?

**Comment by jgeboski** [comment]
Any update on this issue?

**Comment by dequis** [comment]
It was just a routing issue that happened that one day, not a single report of it afterwards. I'm closing it, add a comment if it still happens.
