### ISSUE TITLE
Image support

### ISSUE THREAD

**Issue by rr-** [jgeboski/bitlbee-facebook#64]
I received a pair of images that were rendered like this in irssi:

    <[fb]kosti> <img id="1">
    <[fb]kosti> <img id="2">

When I logged to the website, it was rendered correctly.

I'd expect `bitlbee-facebook` to convert it to a copyable/clickable URL, or at least not to cut off the rest of the HTML.

**Comment by jgeboski** [comment]
Are you sure you're not using the libpurple plugin instead?

**Comment by rr-** [comment]
Uh, you might be right, it seems I've installed both `purple-facebook` and `bitlbee-facebook`.

**Comment by rr-** [comment]
That was it. Thanks.
