### ISSUE TITLE
unknown protocol

### ISSUE THREAD

**Issue by royalhacker** [jgeboski/bitlbee-facebook#66]
after installing bitlbee-facebook on my manual installation using the guide given in readme.md i still receive an error unknown protocol . i am on linuxmint 17.0.3 and using pidgin on bitlbee 3.4.1 .

**Comment by jgeboski** [comment]
I would really advise using the [repository](https://jgeboski.github.io/#debian-and-ubuntu), rather than building manually.

**Comment by AdrianKoshka** [comment]
I know this seems like something stupid but after installing bitlbee-facebook did you restart your bitlbee service? Usually after compiling bitlbee-facebook, bitlbee just doesn't automagically see it.

**Comment by royalhacker** [comment]
Yes Adrian i restarted the service by killing the bitlbee process . And jgeboski the repo insatll doesnt work as it depends on bitlbee>3.4.0 and i have a local install .

**Comment by jgeboski** [comment]
As noted in the repository [instructions](https://jgeboski.github.io/#debian-and-ubuntu):

> The bitlbee packages must be used with the [nightly](http://code.bitlbee.org/debian/README.html) repository.

This will fix the 3.4 dependency issue.

**Comment by pinapl** [comment]
If you're still trying, what worked for me was giving ownership of the plugin folder to user/group bitlbee
`chown bitlbee:bitlbee /usr/lib/bitlbee/*`

**Comment by jgeboski** [comment]
@pinapl I think you mean `/var/lib/bitlbee`. Everything in `/usr/lib` should be owned by root, with others having read permissions.

**Comment by pinapl** [comment]
My terminal tells a different story 
https://goo.gl/photos/QTXtj9SusxDkh7cLA

I replaced 'make install' with 'checkinstall' so that dpkg could keep track of the files created during installation. The two steam files in /usr/lib/bitlbee were owned by root:root, so bitlbee couldn't use them. Changing their ownership to bitlbee:bitlbee let bitlbee use them
