### ISSUE TITLE
FB is sending the time back before every message... should we strip it?

### ISSUE THREAD

**Issue by douglas-carmichael** [jgeboski/bitlbee-facebook#67]
I've recently noticed that FB has been sending back the time of every message before the message itself, should we be stripping it or should that be left to the client?

**Comment by jgeboski** [comment]
This is actually a bitlbee feature. If the message is over a minute old, it will show the time stamp before the message. I can only assume this is from offline messages.

In order to disable this feature, run the following in `&bitlbee`.
```
set display_timestamps false
```
