### ISSUE TITLE
Offline -> /away

### ISSUE THREAD

**Issue by kousu** [jgeboski/bitlbee-facebook#70]
If I WHOIS someone who is offline I get told they are actually away with status "User is offline":
```
TO SERVER: WHOIS SansaOrange
FROM SERVER: :im.codemonkey.be 311 kousu SansaOrange 615712152 facebook * :Sansa Orange
command: whoisuser, source: im.codemonkey.be, target: kousu, arguments: ['SansaOrange', '615712152', 'facebook', '*', 'Sansa Orange'], tags: None
FROM SERVER: :im.codemonkey.be 312 kousu SansaOrange annamanananigggg. :facebook network
command: whoisserver, source: im.codemonkey.be, target: kousu, arguments: ['SansaOrange', 'annamanananigggg.', 'facebook network'], tags: None
FROM SERVER: :im.codemonkey.be 301 kousu SansaOrange :User is offline
command: away, source: im.codemonkey.be, target: kousu, arguments: ['SansaOrange', 'User is offline'], tags: None
FROM SERVER: :im.codemonkey.be 318 kousu SansaOrange :End of /WHOIS list
command: endofwhois, source: im.codemonkey.be, target: kousu, arguments: ['SansaOrange', 'End of /WHOIS list'], tags: None
```
(these logs are from [libirc](https://github.com/jaraco/irc) by the way)

However, if I ISON them they do not show up in the result.

Please give `nosuchnick` (IRC command 401) which is the IRC equivalent of offline instead of claiming they are just away.

**Comment by dequis** [comment]
This isn't related to bitlbee-facebook. It's how bitlbee works. Use the bitlbee tracker if you think there's a bug.

Offline nicks are shown as away because they still exist and you can still message them in most protocols, including facebook.

**Comment by jgeboski** [comment]
Closing as this is outside the scope of this plugin.
