### ISSUE TITLE
Autojoin new groupchats (that are started by somebody else)

### ISSUE THREAD

**Issue by goiken** [jgeboski/bitlbee-facebook#71]
How would I do it?

**Comment by jgeboski** [comment]
I think you want: `account facebook set group_chat_open true`

**Comment by goiken** [comment]
Nops. Doesn't worrk for me.

**Comment by jgeboski** [comment]
What version of the plugin are you using?

**Comment by goiken** [comment]
How can I check?

**Comment by jgeboski** [comment]
How did you install the plugin?

**Comment by goiken** [comment]
built from source

**Comment by jgeboski** [comment]
What is the date attached to `libfacebook.so`?

**Comment by goiken** [comment]
where's that one supposed to sit?

**Comment by goiken** [comment]
Just did `git pull`, `./autogen.sh`, `make` and `make install`. Still same problem.

**Comment by jgeboski** [comment]
Post the output of `account facebook set`.

**Comment by goiken** [comment]
<root> auto_connect = `true'
<root> auto_reconnect = `true'
<root> away is empty
<root> group_chat_open = `true'
<root> mark_read = `false'
<root> nick_format is empty
<root> nick_source = `handle'
<root> password = `********' (hidden)
<root> show_unread = `false'
<root> sync_interval = `30'
<root> tag = `facebook'
<root> username = ****

**Comment by jgeboski** [comment]
Confirmed as a bug.

**Comment by dequis** [comment]
Okay, there was no bug, just a documentation issue.

To get the desired behavior you have to set it to "all" instead of "true".

"true" only autojoins known groupchats, "all" creates new channels which is what this ticket was about. I've updated this page https://wiki.bitlbee.org/HowtoFacebookMQTT#group_chat_open
