### ISSUE TITLE
Bitlbee thinks my messages I send from the web and Android are messages from my friends

### ISSUE THREAD

**Issue by Hund** [jgeboski/bitlbee-facebook#77]
Bitlbee thinks my messages I send from the web and Facebook Messenger (Android) are messages from my friends. So every time I send a message to a friend Bitlbee notifies me about a new message from that friend.  As you can imagine, this gets annoying rather quickly. :)

* Arch Linux
* Bitlbee 3.4.2
* bitlbee-facebook 1.0.0

Not sure how to debug this?

**Comment by dequis** [comment]
http://wiki.bitlbee.org/SelfMessages

**Comment by Hund** [comment]
What? That's not what I'm talking about.

![](http://i.imgur.com/DSV8RCH.png)

This is me sending a messages from Bitlbee and then a second message from the website.

**Comment by dequis** [comment]
Well, we're talking about the same feature, and the workarounds in that page would probably "work" anyway. But that looks like weechat, so your issue is probably different. Did you upgrade from bitlbee 3.4.1 to 3.4.2 without rebuilding bitlbee-facebook? If so, rebuild it.

**Comment by Hund** [comment]
Oh, sorry. :) Rebuilding the bitlbee-facebook solved the problem. Thank you for the help!
