### ISSUE TITLE
Some messages received twice

### ISSUE THREAD

**Issue by toogy** [jgeboski/bitlbee-facebook#8]
Sometimes a message is displayed twice. Looks like it is like if it was received twice (don't know what's happening behind).

It happens rarely enough for it not to be too constraining but I just wanted to report it. ^.^

**Comment by jgeboski** [comment]
I have not seen this myself, and as result cannot recreate the issue.  If you can, obtain the debugging output (see the README) when this occurs.

**Comment by toogy** [comment]
It actually happened something like 3 times. I'll come back here if I can recreate it.

**Comment by dequis** [comment]
Anything new in this one? Could anyone else reproduce it?

**Comment by toogy** [comment]
It still happens from time to time. Would be surprised to be the only one.

**Comment by andreimarcu** [comment]
I was able to reproduce it. I just installed the plugin today.

**Comment by jgeboski** [comment]
I have not seen this happening, which is kind of inconvenient for the sake of debugging.  That said, to be able to do anything about the issue, I am really going to need debugging out.  If either of you can obtain and provide the debugging output, that would be great.

**Comment by toogy** [comment]
I think this comes from Facebook Messenger protocol. I also receive the messages twice on the Messenger app on my phone when it happens (but on desktop they show up once).

**Comment by dequis** [comment]
Oh, nice. That means we can murder this ticket \o/. Thanks!

**Comment by jgeboski** [comment]
I have yet to experience this issue.  I wonder if it is related to the fact that I do not use the Messenger application.

**Comment by jgeboski** [comment]
This should mostly be resolved as of 1952710.
